title = 'MeFi mod log archive'
languageCode = 'en-GB'

[pagination]
pagerSize = 100

[taxonomies]
tag = 'tags'

[[module.imports]]
path = 'github.com/jmooring/hugo-module-archive'

[params.modules.archive]
section = '/posts/'   # The section for which to build archive pages.
prefix = '/archive/'  # The URL prefix for archive pages.
paginate = false      # Whether to paginate archive pages.
navigation = false    # Whether to display previous and next buttons on archive pages.

[params.modules.archive.formats]
year = "2006"
month = "January 2006"
day = "2 January 2006"
