title = 'MeFi mod log archive'
languageCode = 'en-GB'

[taxonomies]
tag = 'tags'

[pagination]
pagerSize = 100

[services.rss]
limit = 100

[[module.imports]]
path = 'github.com/jmooring/hugo-module-archive'

[params.modules.archive]
section = '/posts/'   # The section for which to build archive pages.
prefix = '/archive/'  # The URL prefix for archive pages.
paginate = false      # Whether to paginate archive pages.
navigation = false    # Whether to display previous and next buttons on archive pages.
enableDaily = false   # Whether to generate daily archives.

[params.modules.archive.formats]
year = "2006"
month = "January 2006"
day = "2 January 2006"

# https://github.com/jmooring/hugo-module-archive/discussions/3#discussioncomment-13118489
[[cascade]]
outputs = ['html']
[cascade.target]
path = '{/archive,/archive/**}'
