baseURL = 'https://klipspringr.github.io/mefi-mod-log-archive/'
languageCode = 'en-gb'
title = 'MeFi mod log archive'
theme = 'mefi-mod-log'

[pagination]
pagerSize = 100

[taxonomies]
tag = 'tags'
category = 'categories'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "Archives"
url = "/categories"
weight = 3
