name: Ping MetaFilter from GitHub

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v8.0.0

      - run: uv run ping.py
        working-directory: ./check
